# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  customerapi:
    image: customerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7132:7132
      - 5282:5282
